Fix footer
cod3provider/sports-bar pull request #6
Opened 2023-09-01 16:47 UTC by cod3provider

2023-09-03 20:10 UTC, Vlad-Danilchenko commented on src/layout/Footer/Footer.styled.js
> +  line-height: 1;
line-height: normal;

2023-09-03 20:14 UTC, Vlad-Danilchenko requested changes
Please fix Footer.styled

2023-09-04 06:09 UTC, cod3provider commented on src/layout/Footer/Footer.styled.js
> +  line-height: 1;
done

2023-09-04 20:19 UTC, Vlad-Danilchenko approved these changes

2023-09-04 20:19 UTC, merged